name: Secutilities
main: bl4ckscor3.plugin.secutilities.core.Secutilities
version: 1.6
author: bl4ckscor3
description: Several utilities for the official SecurityCraft server "BreakIn' Bad"
commands:
    blockbreak:
        description: Toggle block breaking on/off.
        usage: /<command>
    blockplace:
        description: Toggle block placing on/off.
        usage: /<command>
    colorcodes:
        description: Shows all the chat formatting codes.
        usage: /<command>
        aliases: [cc]
    lampswitch:
        description: Toggles the ability to switch a redstone lamp on/off via rightclicking it.
        usage: /<command>
        aliases: [redstonelamp,ls,rl]
    loctool:
        description: This gives the player a tool which prints out the coordinates of the block rightclicked.
        usage: /<command>
permissions:
    secutil.blockbreak.toggle:
        description: Gives access to the /blockbreak command.
        default: op
    secutil.blockplace.toggle:
        description: Gives access to the /blockplace command.
        default: op
    secutil.colorcodes:
        description: Gives access to the /colorcodes command.
        default: op
    secutil.pvplimit.bypass:
        description: Allows to bypass the fly and speed restriction in the PvP arena.
        default: op
    secutil.lampswitch.toggle:
        description: Gives access to the /lampswitch command.
        default: op
    secutil.loctool.give:
        description: Gives access to the /loctool command.
        default: op
