name: Secutilities
main: bl4ckscor3.plugin.secutilities.core.Secutilities
version: 1.0
author: bl4ckscor3
description: Several utilities for the official SecurityCraft server "BreakIn' Bad"
commands:
    blockbreak:
        description: Toggle block breaking on/off.
        usage: /<command>
permissions:
    blockbreak.toggle:
        description: Gives access to the /blockbreak command.
        