name: Secutilities
main: bl4ckscor3.plugin.secutilities.core.Secutilities
version: 2.15.1
author: bl4ckscor3
description: Several utilities for the official SecurityCraft server "BreakIn' Bad"
depend: [bl4ckkitCore]
commands:
    blockbreak:
        description: Toggle block breaking on/off.
        usage: /<command>
    blockplace:
        description: Toggle block placing on/off.
        usage: /<command>
    colorcodes:
        description: Shows all the chat formatting codes.
        usage: /<command>
        aliases: [cc]
    loctool:
        description: This gives the player a tool which prints out the coordinates of the block rightclicked.
        usage: /<command>
    pvpcountdown:
        description: Starts the countdown for PvP-Arenas. Only useable by command blocks. The coordinates can be used to set a redstoneblock at them after the countdown is over. Removal is manual.
        usage: /<command> [x] [y] [z]
    tp:
        description: Executes /tpo if neccessary.
        usage: /<command> [args]
        aliases: [tp2p,teleport]
    tphere:
        description: Executes /tpohere if neccessary.
        usage: /<command> [args]
        aliases: [s]
    milk:
        description: Removes all potion effects from the (given) player
        usage: /<command> [player]
    uniqueplayers:
        description: Shows the number of unique players that joined the server.
        usage: /<command>
        aliases: [uplayers,players,unique]
    signbreak:
        description: Enables Vauff to break signs.
        usage: /<command>
    leather:
        description: Gives the player the specified leather armor piece with the specified color.
        usage: /<command> <armorpiece> <hexcolor>
    killall:
        description: Disabled.
        usage: /<command> <args>
    butcher:
        description: Disabled.
        usage: /<command> <args>
    togglefloor:
        description: This is not a useful command.
        usage: /<command>
    giveskull:
        description: Gives the specified amount of the specified playerskull to the specified player and checks for arguments.
        usage: /<command> <receiver> <skullowner> <amount>
    creative:
        description: An alternative to Essentials' warp command, designed for the creative world of BreakIn' Bad.
        usage: /<command> <set|delete|list|warpname> [warpname]
        aliases: [c,cwarp]
    maxplayers:
        description: Shows how many players have been online the most at one time on the server.
        usage: /<command>
        aliases: [mp]
permissions:
    secutil.blockbreak.toggle:
        description: Gives access to the /blockbreak command.
        default: op
    secutil.blockplace.toggle:
        description: Gives access to the /blockplace command.
        default: op
    secutil.colorcodes:
        description: Gives access to the /colorcodes command.
        default: op
    secutil.pvplimit.bypass:
        description: Allows to bypass the fly and speed restriction in the PvP arena.
        default: op
    secutil.loctool.give:
        description: Gives access to the /loctool command.
        default: op
    secutil.milk.own:
        description: Gives access to /milk oneself.
        default: op
    secutil.milk.others:
        description: Gives access to /milk others.
        default: op
    secutil.signbreak.use:
        description: Gives access to the /signbreak command.
        default: op
    secutil.leather.use:
        description: Gives access to the /leather command.
        default: op
    secutil.showSJ:
        description: Gives access to see if Vauff silently joins.
        default: op
    secutil.giveskull.use:
        description: Gives access to the /giveskull command.
        default: op
    secutil.cwarp.set:
        description: Gives access to the /creative set [warpname] command.
        default: op
    secutil.cwarp.delete:
        description: Gives access to the /creative delete [warpname] command.
        default: op
    secutil.cwarp.warp:
        description: Gives access to the /creative <warpname> command.
        default: op
